### ISSUE TITLE
Current CI issues

### ISSUE THREAD

**Issue by bilderbuchi** [ralph-group/pymeasure#348]
Let's keep a list of CI issues that are affecting our runs:
* [ ] The paths caught by our sphinx-doctest problem matcher are not picked up correctly by Actions annotations: https://github.com/actions/runner/issues/765
* [ ] There is no support yet for multiline error messages (that e.g. sphinx-doctest produces) in the problem matcher: https://github.com/actions/toolkit/issues/193. As a temporary workaround, we just match the first line for now, which will just show in the CI overview that a problem exists
* [ ] We don't yet use linting (#346) and don't have annotations/actions for flake8
* [ ] We don't have annotations for pytest errors, but maybe that works ootb? If not, search for a problem matcher example.

**Comment by bilderbuchi** [comment]
* [ ] `python setup.py test` is deprecated, and we should move away from that again. see https://github.com/pypa/setuptools/issues/1684 https://github.com/pytest-dev/pytest/issues/5534
   - [ ] We need to undo the related changes from @cjermain's 4357bc73efdaf7c0d9d83234ba5e10cf2c71c9e4
   - [ ] Then identify and implement the currently recommended best practice.

**Comment by bilderbuchi** [comment]
* [ ] See if we can store (at least for a short time) the generated documentation as an artifact so we can check online if docs generation works as expected. So users do not need to run sphinx locally, and devs can check PRs without having to fetch them locally, first.

**Comment by bilderbuchi** [comment]
* [ ] Upgrade GH actions plugin version to 3: https://github.com/actions/cache/releases/tag/v3.0.0

**Comment by bilderbuchi** [comment]
* [ ] We could start adding pydocstyle checking to CI. Enable "D212 | Multi-line docstring summary should start at the first line"
